### ISSUE TITLE
support for template @param

### ISSUE THREAD

**Issue by yathit** [Non-Dairy-Soy-Plugin/Non-Dairy-Soy-Plugin#17]
Thanks for very valuable plugin.

New closure template use typed parameter. Its support will be great: https://developers.google.com/closure/templates/docs/commands#param

**Comment by dsbecker** [comment]
+1

**Comment by SerCeMan** [comment]
Hi, @yathit!

The support for the `@param` syntax has been added in the new release [0.7.0](https://github.com/Non-Dairy-Soy-Plugin/Non-Dairy-Soy-Plugin/releases/tag/0.7.0). Feel free to reopen the issue if the problem still exists for you.
