### ISSUE TITLE
Build Error - cannot find symbol AliasDeclaration

### ISSUE THREAD

**Issue by tntim96** [Non-Dairy-Soy-Plugin/Non-Dairy-Soy-Plugin#23]
I've checked out IntelliJ 15, built and linked in the JARs, but the project seems to be missing the class `AliasDeclaration`:
`Error:(35, 24) java: cannot find symbol
  symbol:   class AliasDeclaration
  location: class net.venaglia.nondairy.soylang.lexer.cupparser.structure.TemplateFile`

I suspected I needed to download the [v0.11a CUPs JAR](http://www2.cs.tum.edu/projects/cup/) to apply to `test/net/venaglia/nondairy/soylang/lexer/cupparser/soy.cup`, but am not sure where to place the generated classes, or if there is just another JAR I need to add to the class-path.

Is there a script I need to run to generate the `AliasDeclaration` class? I'm happy to add some build-instructions to your README.md file once I get this working.

**Comment by SerCeMan** [comment]
The issue has been resolved. You can build the plugin with gradle now.
