### ISSUE TITLE
Template call param tag doesn't expect kind attribute

### ISSUE THREAD

**Issue by davidblumenthal** [Non-Dairy-Soy-Plugin/Non-Dairy-Soy-Plugin#28]
The closure compiler requires a kind attribute on lock-form 'param' commands when in strict mode
(See https://developers.google.com/closure/templates/docs/security#usage).

However, this plugin does not expect this attribute and reports an error when it sees the attribute defined:

> Unexpected token in param tag

`{call .assessmentTypePickerCell}
      {param title kind="text"}Admin Assistant{/param}
 {/call}`
It should allow the attribute.

**Comment by SerCeMan** [comment]
Hi, @davidblumenthal!

The issue has been fixed with the new release [0.7.0](https://github.com/Non-Dairy-Soy-Plugin/Non-Dairy-Soy-Plugin/releases/tag/0.7.0). Feel free to reopen the issue if the problem still exists for you.
