### ISSUE TITLE
Error in IntelliJ crash whole application

### ISSUE THREAD

**Issue by Richardb953** [Non-Dairy-Soy-Plugin/Non-Dairy-Soy-Plugin#29]
9:01	Throwable
		Unbalanced tree. Most probably caused by unbalanced markers. Try calling setDebugMode(true) against PsiBuilder passed to identify exact location of the problem
		language: Language: ClosureTemplate,

**Comment by SerCeMan** [comment]
Hi, @ryanseys!

The issue has been fixed with the new release [0.7.1](https://github.com/Non-Dairy-Soy-Plugin/Non-Dairy-Soy-Plugin/releases/tag/0.7.1). Feel free to reopen the issue if the problem still exists for you.
